import { Pergunta } from "./pergunta.model";

export const Perguntas: Pergunta[] = [
    { id: 1, descricao: 'A Trissomia do 21 (Síndrome de Down) é uma doença?', resposta: false, 
    descricaoResposta: 'Mito! A T21 não é uma doença e não deve ser tratada como tal. É uma mutação cromossômica no cromossomo 21 causando a sua trissomia.'},
    { id: 2, descricao: 'Ela tem cura?', resposta: false,
    descricaoResposta: 'Mito! A Trissomia do 21 não é uma doença que através de algum procedimento pode se modificar. Porém, diversas ações, ou melhor, terapias podem auxiliar no processo de estimulação da pessoa com T21 para que possa ser um adulto independente.'},
    { id: 3, descricao: 'Pessoas com a T21 (Síndrome de Down) falam e andam?', resposta: true,
    descricaoResposta: 'Verdade! A pessoa com T21 possui hipotonia na musculatura corporal, incluindo também a língua que é um músculo. Assim, existe a dificuldade natural trazida pelo cromossomo para o pleno desenvolvimento dessas áreas, porém, a estimulação precoce com as terapias de fonoaudiologia e fisioterapia garantem às pessoas com T21 o desenvolvimento da fala e motor.'},
    { id: 4, descricao: 'Apenas pessoas brancas podem nascer com a Trissomia do 21?', resposta: false,
    descricaoResposta: 'Mito! Por ser uma mutação cromossômica, a T21 não possui relação alguma com cor e raça. Pode acontecer casos de T21 em qualquer família.'},
    { id: 5, descricao: 'As pessoas com a T21 apresentam atraso no desenvolvimento da linguagem?', resposta: true,
    descricaoResposta: 'Verdade! Há um atraso no desenvolvimento da linguagem atribuído a hipotonia do músculo da língua e ao déficit cognitivo. Porém, a estimulação com as terapias, indicadas pelo profissional que acompanha a pessoa com T21, contribuem para o processo de desenvolvimento da fala.'},
    { id: 6, descricao: 'As pessoas com a T21 são agressivas?', resposta: false,
    descricaoResposta: 'Mito! Não podemos generalizar o comportamento das pessoas com a T21, determinando certos comportamentos, pois essa afirmação gera preconceito e estigma. Cada indivíduo tem suas características e devem ser percebidos na sua singularidade.'},
    { id: 7, descricao: 'Pessoas com a Trissomia do 21 adoecem mais??', resposta: true,
    descricaoResposta: 'Verdade! Ocasionalmente, como consequência de baixa resistência imunológica, as crianças com Síndrome de Down, principalmente nos primeiros anos de vida, são mais susceptíveis a infecções, principalmente no sistema respiratório e digestivo. Esta propensão vai diminuindo com o passar da idade.'},
    { id: 8, descricao: 'As crianças devem frequentar escola especial?', resposta: false,
    descricaoResposta: 'Mito! As crianças com T21 assim como crianças com qualquer tipo de deficiência devem, por lei, frequentar o ensino regular e participar do Ensino Educacional Especializado no contra turno.'},
    { id: 9, descricao: 'Pessoas com a Trissomia do 21 podem praticar esporte?', resposta: true,
    descricaoResposta: 'Verdade! As pessoas com a T21, assim como qualquer pessoa, podem e devem praticar atividade física para seu bem-estar físico e emocional desde que sejam de conhecimento e acompanhamento do seu médico.'},
    { id: 10, descricao: 'Elas têm a sexualidade mais aflorada?', resposta: false,
    descricaoResposta: 'Mito! Por recebem poucas informações sobre sexualidade e terem poucas oportunidades de socialização, a expressão considerada inadequada dos desejos sexuais nas pessoas com deficiência, refere-se à manifestação da sexualidade de um modo grosseiro que não correspondente às regras sociais. Assim, o desejo, que é normal em todo ser humano, aparece como diferenciado e exagerado pela sua exteriorização inadequada.'},
    { id: 11, descricao: 'As pessoas com T21 são assexuadas?', resposta: false,
    descricaoResposta: 'Mito! Ao considerar a pessoa com T21 como alguém não dotado de sexualidade, negligenciam-se os cuidados contra situações de abuso e se omitem a essas pessoas o direito de acesso à orientação sexual. Esse comportamento familiar contribui para o elevado índices de violência, gravidez indesejada e doenças sexualmente transmissíveis, nesta população.'},
  ];